### ISSUE TITLE
Could you provide the hyper parameter used to conduct the experiments on CIFAR-10 datasets

### ISSUE THREAD

**Issue by nuwuxian** [YivanZhang/lio#1]
I notice that the you set the transition_type = 'none' and regularization_type = 'none' in the file ex.py. I am wondering what's the default value to run the experiments in cifar-10 datasets. I guess that the transition_type should be dirichlet and the regularization_type should be tv. By the way, what about the value of num_iter_test. In your current version, you only test 10 times.

**Comment by YivanZhang** [comment]
Thank you for your interest and questions.

We used [sacred](https://github.com/IDSIA/sacred) to configure and organize our experimental settings. If you want to run an experiment on the CIFAR-10 dataset, with symmetric noise, using total variation regularization and Dirichlet posterior estimate, you can use the [command-line interface](https://sacred.readthedocs.io/en/stable/command_line.html) of sacred and run 
```sh
python ex.py with dataset_name=cifar10 noise_type=symm transition_type=dirichlet regularization_type=tv
```

You can also run it with Python using [updated configs](https://sacred.readthedocs.io/en/stable/configuration.html#updating-config-entries):
```python
ex.run(config_updates={
    'dataset_name': 'cifar10',
    'noise_type': 'symm',
    'transition_type': 'dirichlet',
    'regularization_type': 'tv',
})
```
In this way, you can use Python to generate all combinations of configs that you want to use.

As for `num_iter_test`, yes, we only tested 10 times. We used an iteration-based rather than epoch-based recording, which might be slightly different from other works. I personally prefer it because of easier learning rate scheduling. You can modify the `run` and `config` functions in `ex.py` to make it an epoch-based iteration if you like.

Thanks again for your interest in our work. Please let us know if you need any further information.
